<a href="https://colab.research.google.com/github/valentinvalhondo/Colab-Notebooks/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is a Python library for creating and manipulating vectors and matrices. 

In [ ]:
import numpy as np

In [ ]:
print(np.array([1.1, 2.2, 3.3, 4.4, 5.5]))

[1.1 2.2 3.3 4.4 5.5]


In [ ]:
print(np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]]))

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
tensor = np.zeros((2,3,4), dtype=int)

In [ ]:
tensor[1][1] = [1, 2, 3, 4]
print(tensor)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [1 2 3 4]
  [0 0 0 0]]]


In [ ]:
# Populate matrices with random numbers across certain ranges
print(np.random.randint(low=50, high=101, size=(6)))
# To create random floating-point values between 0.0 and 1.0, call
print(np.random.random([6]))

[100  82  68  84  77  84]
[0.79936462 0.23301399 0.47291583 0.52631691 0.77648789 0.68892372]


In [ ]:
matrix_2x3 = np.arange(1, 7).reshape(2, 3)
print(matrix_2x3)
print('-')
matrix_3x1 = np.arange(7, 10).reshape(3, 1)
print(matrix_3x1)

[[1 2 3]
 [4 5 6]]
-
[[7]
 [8]
 [9]]


In [ ]:
matrix_3x1 ** 2

array([[49],
       [64],
       [81]])

In [ ]:
# Compatible matrix product ( use @ or .dot(B) )
matrix_2x1 = matrix_2x3 @ matrix_3x1
print(matrix_2x1)

[[ 50]
 [122]]


In [ ]:
# Operations with matrices
matrix_2x3.max()
matrix_2x3.sum()
matrix_2x3.sum(axis=1)
matrix_2x3.min()
# Transposition 
matrix_2x3.T
# a.*b (matlab) = a*b (numpy)
# a./b (matlab) = a/b (numpy)
# a.^3 (matlab) = a**3 (numpy)
# inv(a) (matlab) = linalg.inv(a) (python)
# a\b (matlab) = linalg.solve(a,b) (python)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Universal functions
np.exp(matrix_2x3)
np.sqrt(matrix_2x3)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

#Copies and Views

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:


In [ ]:
# No Copy at All - Simple assignments make no copy of objects or their data.
A = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])
B = A
B is A # A and B are two names for the same array object
print(A)
B[1] = 5
print(A)
# Python passes mutable objects as references, so function calls make no copy.

[1.1 2.2 3.3 4.4 5.5 6.6]
[1.1 5.  3.3 4.4 5.5 6.6]


In [ ]:
# View or Shallow Copy - Different array objects can share the same data. 
# The view method creates a new array object that looks at the same data.

C = A.view()
C is A

False

In [ ]:
C.base is A # C is a view of the data owned by A

True

In [ ]:
# A's shape doesn't change
C = C.reshape((2, 3))
print(C.shape, ' C vs A ', A.shape)
# A's data changes
C[(1,2)] = 0
print(A)

(2, 3)  C vs A  (6,)
[1.1 5.  3.3 4.4 5.5 0. ]


In [ ]:
# Deep Copy - The copy method makes a complete copy of the array and its data.
A = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])
D = A.copy()
print(D is A)
print(D.base is A)
# Both are false, because D doesn't share anything with A

False
False


In [ ]:
# Sometimes copy should be called after slicing if the original array
#  is not required anymore
a = np.arange(int(1e8))
b = a[:100].copy()
del a  # the memory of ``a`` can be released.

# Exercises for NumPy codelab for ML course

In [ ]:
# Task 1
feature = np.arange(6,21)
print(feature)
label = 3 * feature + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
# Task 2
noise = (np.random.random([label.size]) * 4) - 2
print(noise)
label = label + noise
print(label)

[ 0.09549756 -1.0622287  -1.25902666 -0.4832493   1.4965093   1.9994388
  0.53596482  1.42083821  0.20779989 -0.55961939 -1.06222261  1.01382964
 -1.44014506  0.22403746 -1.16743376]
[22.09549756 23.9377713  26.74097334 30.5167507  35.4965093  38.9994388
 40.53596482 44.42083821 46.20779989 48.44038061 50.93777739 56.01382964
 56.55985494 61.22403746 62.83256624]
